export default {
  hi: "Hi, I am ",
  hi2: "",
  name: "farzad Enayati",
  home: "HOME",
  about: "ABOUT",
  resume: "RESUME",
  portfolios: "PORTFOLIOS",
  contact: "CONTACT",
  aboutme: "ABOUT ME",
  services: "SERVICES",
  age: "Age",
  nationality: "Nationality",
  languages: "Languages",
  phone: "Phone",
  years: "Years",
  personalweb: "Personal web",
  contactme: "CONTACT ME",
  PageNotFound: "Page not found!",
  bestwish: "Wish you all the best wishes.",
  portfolioDesc: "You can see farzad Enayati's portfolio in this page.",
  resumeDesc: "You can see farzad Enayati's resume in this page.",

  contactinfo: "Contact Details",
  downloadCv: "Download the full resume",
  myskills: "MY SKILLS",
  workingexperience: "Working Experience",
  educationalqualifications: "Educational Qualifications",
  resumeNote: "The work experiences mentioned above are related to recent years, and to see the full resume, you can download the  resume from the link below.",
  note: "Note"
}